# Ansible Inventory - Auto-generated by Terraform

[jenkins]
jenkins ansible_host=${jenkins_ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/microservices-cicd

[microservices]
%{ for idx, ip in microservices_ips ~}
${microservices_names[idx]} ansible_host=${ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/microservices-cicd
%{ endfor ~}

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
