---
# Common role - Basic server configuration

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: Install common packages
  apt:
    name:
      - curl
      - wget
      - git
      - vim
      - htop
      - net-tools
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - python3
      - python3-pip
      - python3-setuptools
      - jq
    state: present

- name: Set timezone to UTC
  timezone:
    name: UTC

- name: Configure system limits
  pam_limits:
    domain: '*'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop:
    - { limit_type: 'soft', limit_item: 'nofile', value: '65536' }
    - { limit_type: 'hard', limit_item: 'nofile', value: '65536' }
    - { limit_type: 'soft', limit_item: 'nproc', value: '65536' }
    - { limit_type: 'hard', limit_item: 'nproc', value: '65536' }

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    state: absent

- name: Create application directory
  file:
    path: /opt/microservices
    state: directory
    mode: '0755'
