# Prometheus Configuration

global:
  scrape_interval: 15s  # How frequently to scrape targets
  evaluation_interval: 15s  # How frequently to evaluate rules
  external_labels:
    cluster: 'microservices-cicd'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - 'alerts.yml'

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter - System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          type: 'system'

  # cAdvisor - Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
          type: 'containers'

  # API Gateway Service
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
        labels:
          service: 'api-gateway'
          type: 'application'
          language: 'nodejs'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
        labels:
          service: 'auth-service'
          type: 'application'
          language: 'python'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Product Service
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3002']
        labels:
          service: 'product-service'
          type: 'application'
          language: 'nodejs'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Order Service
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3003']
        labels:
          service: 'order-service'
          type: 'application'
          language: 'python'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Production Servers (when deployed to AWS)
  # Uncomment and configure when deploying to production
  # - job_name: 'production-nodes'
  #   ec2_sd_configs:
  #     - region: us-east-1
  #       port: 9100
  #       filters:
  #         - name: tag:Role
  #           values:
  #             - microservices
  #   relabel_configs:
  #     - source_labels: [__meta_ec2_tag_Name]
  #       target_label: instance
  #     - source_labels: [__meta_ec2_private_ip]
  #       target_label: private_ip
